= Spock framework and JUnit 5, Unit and Integration tests separation, Parallel tests execution in Maven

A sample Maven project combining http://spockframework.org/[Spock] and https://junit.org/junit5/[JUnit 5] tests, parallel test execution and separation between Unit and Integration tests.

===== Based on:

* https://github.com/SanderSmee/spock-jupiter[Spockframework and JUnit5] by https://github.com/SanderSmee[SanderSmee]
* https://github.com/alimate/maven-source-sets[Different Source Sets for Different Test Types] by https://github.com/alimate[Ali Dehghani]

== Dependencies and Plugins

* JDK 14.01 (Java version set to **13** in pom.xml)
* Apache Maven 3.6.3
* https://groovy-lang.org/[Apache Groovy] - https://mvnrepository.com/artifact/org.codehaus.groovy/groovy-all[3.0.3]
* http://spockframework.org/[Spock Framework] - https://mvnrepository.com/artifact/org.spockframework/spock-core[2.0-M2-groovy-3.0]
* https://github.com/groovy/groovy-eclipse/wiki/Groovy-Eclipse-Maven-plugin[Groovy Eclipse Compiler Plugin] - https://mvnrepository.com/artifact/org.codehaus.groovy/groovy-eclipse-compiler[3.6.0-03]
* https://github.com/groovy/groovy-eclipse/wiki/Building-Maven-Batch-Compiler[Groovy Eclipse Batch Compiler] - https://mvnrepository.com/artifact/org.codehaus.groovy/groovy-eclipse-batch[3.0.3-01]

* https://mvnrepository.com/artifact/org.junit.jupiter/junit-jupiter-engine[JUnit Jupiter Engine 5.6.2]
* https://mvnrepository.com/artifact/org.junit.jupiter/junit-jupiter-params[JUnit Jupiter Params 5.6.2]
* https://mvnrepository.com/artifact/org.junit.platform/junit-platform-runner[JUnit Platform Runner 1.6.2]

* https://maven.apache.org/plugins/maven-compiler-plugin/[Apache Maven Compiler Plugin] - https://mvnrepository.com/artifact/org.apache.maven.plugins/maven-compiler-plugin[3.8.1]
* https://maven.apache.org/surefire/maven-surefire-plugin/[Maven Surefire Plugin] - https://mvnrepository.com/artifact/org.apache.maven.plugins/maven-surefire-plugin[3.0.0-M4]
* https://maven.apache.org/surefire/maven-failsafe-plugin/[Maven Failsafe Plugin] - https://mvnrepository.com/artifact/org.apache.maven.plugins/maven-failsafe-plugin[3.0.0-M4]
* https://www.mojohaus.org/build-helper-maven-plugin/[Build Helper Maven Plugin] - https://mvnrepository.com/artifact/org.codehaus.mojo/build-helper-maven-plugin[3.1.0]

== Project Structure

```
src
    main
        java - source code
        resources - application resources
    test
        integration - integration tests
        resources - test resources
        unit - unit test
```

== Recommended File Name Patterns

* *Java* Unit test:
. `*Test.java`
. `*TestCase.java`
. `*Tests.java`
. `Test*.java`
* *Java* Integration test:
. `IT*.java`
. `*IT.java`
. `*ITCase.java`
* *Spock/Groovy* Unit test:
. `*Spec.groovy`
* *Spock/Groovy* Integration test:
. `*IS.groovy`

== Forked Test Execution

Latest Spock `1.3-groovy-2.5` cannot execute test classes in parallel mode and that should be fixed in version `2.0`.
Until then a workaround is available:

```xml
<plugins>
[...]
  <plugin>
    <groupId>org.apache.maven.plugins</groupId>
    <artifactId>maven-surefire-plugin</artifactId> // same for maven-failsafe-plugin
    [...]
    <configuration>
        <forkCount>2C</forkCount>
        <reuseForks>false</reuseForks>
        [...]
    </configuration>
  </plugin>
[...]
</plugins>
```

https://maven.apache.org/surefire/maven-surefire-plugin/examples/fork-options-and-parallel-execution.html?Forked%20Test%20Execution[Documentation]

== JUnit 5 Parallel Execution

Global settings are defined in +
    `src/test/resources/junit-platform.properties`

```properties
junit.jupiter.execution.parallel.enabled=true
junit.jupiter.execution.parallel.config.strategy=dynamic
junit.jupiter.execution.parallel.config.dynamic.factor=2
junit.jupiter.execution.parallel.mode.default=concurrent
junit.jupiter.execution.parallel.mode.classes.default=concurrent
```

Fine tune per class or for single methods by annotation: +
 `@Execution(ExecutionMode.CONCURRENT)` +
 `@Execution(ExecutionMode.SAME_THREAD)`

https://junit.org/junit5/docs/snapshot/user-guide/#writing-tests-parallel-execution[Documentation]

== Spock Tests and Parallel Execution

Spock `1.3-groovy-2.5` is based on JUnit 4 and *doesn't support* parallel execution within a spec. +
Spock 2.0 will be based on the JUnit 5 Platform according to https://github.com/spockframework/spock/tree/spock-2.0[documentation] and is expected to support parallel tests execution.

== Spock Configuration

`src/test/resources/SpockConfig.groovy`

```groovy
runner {
    filterStackTrace false
    optimizeRunOrder true
}
```

http://spockframework.org/spock/docs/1.3/extensions.html[Documentation]

== Useful Resources

* http://docs.groovy-lang.org/latest/html/documentation/tools-groovyc.html#_maven_integration[Groovy Eclipse Maven plugin vs. GMavenPlus], https://github.com/groovy/GMavenPlus[GMavenPlus]
* https://github.com/junit-team/junit5-samples/tree/r5.5.2/junit5-jupiter-starter-maven[junit5-jupiter-starter-maven] - how to execute JUnit Jupiter tests using Maven
* https://junit.org/junit5/docs/5.4.0-M1/user-guide/index.html[JUnit 5 User Guide]
* http://antkorwin.com/junit5/junit5_parallel_execution.html[JUnit5 Parallel Execution of tests]
* https://www.baeldung.com/maven-junit-parallel-tests[Running JUnit Tests in Parallel with Maven]
* https://www.baeldung.com/maven-integration-test[Integration Testing with Maven]
* https://www.petrikainulainen.net/programming/testing/writing-unit-tests-with-spock-framework-creating-a-maven-project/[Writing Unit Tests With Spock Framework: Creating a Maven Project]
* https://www.testwithspring.com/lesson/running-unit-tests-with-maven-spock-edition/[Running Unit Tests With Maven – Spock Edition]
* https://www.testwithspring.com/lesson/running-end-to-end-tests-with-maven-spock-edition/[Running End-to-End Tests With Maven – Spock Edition]
* https://www.baeldung.com/spring-spock-testing[Testing with Spring and Spock]
* https://github.com/spockframework/spock-example[Spock Framework Example Project]
* https://medium.com/@mzimecki/maven-project-with-java-groovy-spock-and-junit-1dc5e52aa38[Maven Project With Java, Groovy, Spock And JUnit]
* https://stackoverflow.com/a/61881671/7598851[JUnit 4 + Spock 2 (Groovy 2.5), JUnit 5 + Spock 2 (Groovy 2.5)] - StackOverflow answer by #kriegaex#
* https://github.com/spockframework/spock/issues/1166[Add migration guide Spock 1.x → 2.x to manual or separate document] - Spock issue #1166

== Optional Extensions

==== Maven Surefire Report Plugin

* https://maven.apache.org/surefire/maven-surefire-report-plugin/[Documentation]
* Usage:
. `mvn clean verify site` +
. Open `target/site/index.html` in Web browser
* Setup

```xml
<project>
    [...]

    <build>
        [...]

        <plugins>
            [...]

            <!-- https://mvnrepository.com/artifact/org.apache.maven.plugins/maven-site-plugin -->
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-site-plugin</artifactId>
                <version>3.8.2</version>
            </plugin>

            <!-- https://mvnrepository.com/artifact/org.apache.maven.plugins/maven-project-info-reports-plugin -->
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-project-info-reports-plugin</artifactId>
                <version>3.0.0</version>
            </plugin>
        </plugins>
    </build>

    <reporting>
        <plugins>
            <!-- https://mvnrepository.com/artifact/org.apache.maven.plugins/maven-pmd-plugin -->
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-pmd-plugin</artifactId>
                <version>3.12.0</version>
            </plugin>

            <!-- https://mvnrepository.com/artifact/org.apache.maven.plugins/maven-surefire-report-plugin -->
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-surefire-report-plugin</artifactId>
                <version>2.22.2</version>
            </plugin>
        </plugins>
    </reporting>

</project>
```

==== JaCoCo Plugin

* https://www.jacoco.org/jacoco/index.html[Documentation]
* Usage:
. `mvn clean verify`
. Open `target/site/jacoco/index.html` in Web browser
* Setup

```xml
<project>
    [...]

    <build>
        [...]

        <plugins>
            [...]

            <!-- https://mvnrepository.com/artifact/org.jacoco/jacoco-maven-plugin -->
            <plugin>
                <groupId>org.jacoco</groupId>
                <artifactId>jacoco-maven-plugin</artifactId>
                <version>0.8.4</version>
                <executions>
                    <execution>
                        <goals>
                            <goal>prepare-agent</goal>
                        </goals>
                    </execution>
                    <execution>
                        <id>report</id>
                        <phase>prepare-package</phase>
                        <goals>
                            <goal>report</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>

</project>
```